import {Component,ViewChild,ElementRef,ComponentFactoryResolver,ViewContainerRef,forwardRef,ContentChildren,QueryList} from '@angular/core';
import { base } from './base';
// Ext Class - Ext.MessageBox
class messageboxMetaData {
	public static XTYPE: string = 'messagebox';
	public static INPUTNAMES: string[] = [
		'activeItem',
		'alwaysOnTop',
		'anchor',
		'anchorPosition',
		'autoDestroy',
		'axisLock',
		'baseCls',
		'bind',
		'bodyBorder',
		'bodyPadding',
		'border',
		'bottom',
		'buttons',
		'buttonToolbar',
		'cardSwitchAnimation',
		'centered',
		'closable',
		'closeAction',
		'closeToolText',
		'cls',
		'contentEl',
		'control',
		'controller',
		'data',
		'defaultListenerScope',
		'defaults',
		'defaultTextHeight',
		'defaultType',
		'disabled',
		'docked',
		'draggable',
		'enter',
		'enterAnimation',
		'exit',
		'exitAnimation',
		'flex',
		'floated',
		'fullscreen',
		'header',
		'height',
		'hidden',
		'hideAnimation',
		'hideOnMaskTap',
		'html',
		'icon',
		'iconCls',
		'id',
		'itemId',
		'items',
		'keyMap',
		'keyMapEnabled',
		'keyMapTarget',
		'layout',
		'left',
		'listeners',
		'manageBorders',
		'margin',
		'masked',
		'maxHeight',
		'maxWidth',
		'message',
		'minHeight',
		'minWidth',
		'modal',
		'msg',
		'padding',
		'plugins',
		'prompt',
		'publishes',
		'record',
		'reference',
		'referenceHolder',
		'relative',
		'renderTo',
		'right',
		'scrollable',
		'session',
		'shadow',
		'shim',
		'showAnimation',
		'stretchX',
		'stretchY',
		'style',
		'styleHtmlCls',
		'styleHtmlContent',
		'title',
		'toFrontOnShow',
		'tools',
		'tooltip',
		'top',
		'touchAction',
		'tpl',
		'tplWriteMode',
		'translatable',
		'twoWayBindable',
		'ui',
		'useBodyElement',
		'userCls',
		'viewModel',
		'width',
		'x',
		'xtype',
		'y',
		'zIndex',
		'platformConfig',
		'responsiveConfig',
		'fitToParent',
		'config'
];
	public static OUTPUTS: any[] = [
		{name:'activate',parameters:'newActiveItem,messagebox,oldActiveItem'},
		{name:'add',parameters:'messagebox,item,index'},
		{name:'added',parameters:'messagebox,container,index'},
		{name:'beforehide',parameters:'messagebox'},
		{name:'beforeorientationchange',parameters:''},
		{name:'beforeshow',parameters:'messagebox'},
		{name:'beforetofront',parameters:'messagebox'},
		{name:'deactivate',parameters:'oldActiveItem,messagebox,newActiveItem'},
		{name:'destroy',parameters:''},
		{name:'erased',parameters:'messagebox'},
		{name:'floatingchange',parameters:'messagebox,positioned'},
		{name:'fullscreen',parameters:'messagebox'},
		{name:'hide',parameters:'messagebox'},
		{name:'initialize',parameters:'messagebox'},
		{name:'move',parameters:'messagebox,item,toIndex,fromIndex'},
		{name:'moved',parameters:'messagebox,container,toIndex,fromIndex'},
		{name:'orientationchange',parameters:''},
		{name:'painted',parameters:'element'},
		{name:'positionedchange',parameters:'messagebox,positioned'},
		{name:'remove',parameters:'messagebox,item,index'},
		{name:'removed',parameters:'messagebox,container,index'},
		{name:'renderedchange',parameters:'messagebox,item,rendered'},
		{name:'resize',parameters:'element'},
		{name:'show',parameters:'messagebox'},
		{name:'tofront',parameters:'messagebox'},
		{name:'updatedata',parameters:'messagebox,newData'},
		{name:'ready',parameters:''}
];
	public static OUTPUTNAMES: string[] = [
		'activate',
		'add',
		'added',
		'beforehide',
		'beforeorientationchange',
		'beforeshow',
		'beforetofront',
		'deactivate',
		'destroy',
		'erased',
		'floatingchange',
		'fullscreen',
		'hide',
		'initialize',
		'move',
		'moved',
		'orientationchange',
		'painted',
		'positionedchange',
		'remove',
		'removed',
		'renderedchange',
		'resize',
		'show',
		'tofront',
		'updatedata',
		'ready'
];
}
@Component({
  selector: messageboxMetaData.XTYPE,
	inputs: messageboxMetaData.INPUTNAMES,
	outputs: messageboxMetaData.OUTPUTNAMES,
	providers: [{provide: base, useExisting: forwardRef(() => messagebox)}],
	template: '<template #dynamic></template>'
})
export class messagebox extends base {
	constructor(eRef:ElementRef,resolver:ComponentFactoryResolver,vcRef:ViewContainerRef) {
		super(eRef,resolver,vcRef,messageboxMetaData);
	}
	//@ContentChildren(base,{read:ViewContainerRef}) extbaseRef:QueryList<ViewContainerRef>;
	@ContentChildren(base,{read: base}) extbaseRef: QueryList<base>;
	@ViewChild('dynamic',{read:ViewContainerRef}) dynamicRef:ViewContainerRef;
	ngAfterContentInit() {this.AfterContentInit(this.extbaseRef);}
	ngOnInit() {this.OnInit(this.dynamicRef,messageboxMetaData);}
}
